<?php


namespace TerekhinDevelopment\short_codes\src\impl;


use TerekhinDevelopment\short_codes\src\ITD_ShortCodes;
use TerekhinDevelopment\short_codes\src\TD_ShortCodes;

class TD_News_Feed_ShortCode extends TD_ShortCodes implements ITD_ShortCodes
{
    private $default_attr = array(
        'display_categories'=>'no',
        'image_size'=>'none',
        'custom_image_width'=>'',
        'custom_image_height'=>'',
        'show_date'=>'yes',
        'date_format'=>'F d',
        'date_location'=>'before_title',
        'display_comments'=>'yes',
        'display_views'=>'yes',
        'title_tag'=>'h5',
        'space_between_items'=>'no',
        'content_in_grid'=>'yes'

    );

    public function __construct($sc_name)
    {
        parent::__construct($sc_name); // TODO: Change the autogenerated stub
        $this->short_code_title='News Feed';
        $this->css_class = 'td-news-feed';
    }

    function renderShortCode($attr)
    {

    }

    function initShortCode()
    {
        // TODO: Implement initShortCode() method.
    }

    function initAttributes($value, $data)
    {
        // TODO: Implement initAttributes() method.
    }

    private function getParams()
    {

    }

}